### ISSUE TITLE
Is "limit" the right name?

### ISSUE THREAD

**Issue by eyal-ka** [RamanujanMachine/ResearchTools#11]
@RotemKalisch 

Are you sure this is called the limit? I feel like there should be a better name, maybe substitute? 

https://github.com/RamanujanMachine/ResearchTools/blob/0aa31e1247dc5500e235c0677f10729335030e23/ramanujan/matrix.py#LL48C11-L48C11

**Comment by RotemKalisch** [comment]
> @RotemKalisch
> 
> Are you sure this is called the limit? I feel like there should be a better name, maybe substitute?
> 
> https://github.com/RamanujanMachine/ResearchTools/blob/0aa31e1247dc5500e235c0677f10729335030e23/ramanujan/matrix.py#LL48C11-L48C11

I'm open to suggestions (@rotelimelech @itaybthl)

**Comment by RotemKalisch** [comment]
Closing this as this code has changed and the issue is irrelevant
