### ISSUE TITLE
Functions that accept list should also accept tuples

### ISSUE THREAD

**Issue by rotelimelech** [RamanujanMachine/ResearchTools#12]
It is reasonable that if ` ramanujan.known_cmfs.pi.trajectory_matrix([1,1])` works, then also ` ramanujan.known_cmfs.pi.trajectory_matrix((1,1))` should work. 

Convert accepted values to lists on other functions that accept the same type of information.

**Comment by RotemKalisch** [comment]
Closing this as the interface has changed since then and now it receives only dicts.
